#!/usr/bin/env bash

# vim
sudo apt-get install -y vim

# autojump
sudo apt-get install -y autojump

# pip
sudo apt-get install -y python3-pip
sudo apt-get install -y python-pip

# clone powerlevel9k theme
sudo git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

# install powerfont
## clone
git clone https://github.com/powerline/fonts.git --depth=1
## install
cd fonts
./install.sh
## clean-up a bit
cd ..
rm -rf fonts